#!/usr/bin/env python3
"""Generates reports/DATA_QUALITY_EVIDENCE.md purely from numbers already
written to disk by run_pipeline.py and generate_analytics_reports.py -
no hand-typed statistics."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd
from src.config import REPORTS_DIR

def main():
    before = pd.read_csv(REPORTS_DIR / "data_quality_before.csv") if (REPORTS_DIR / "data_quality_before.csv").exists() else None
    after = pd.read_csv(REPORTS_DIR / "data_quality_after.csv")
    cleaning = pd.read_csv(REPORTS_DIR / "cleaning_report.csv")
    detail = pd.read_csv(REPORTS_DIR / "cleaning_report_detail.csv")
    relationship = pd.read_csv(REPORTS_DIR / "relationship_quality.csv")
    coverage = pd.read_csv(REPORTS_DIR / "join_coverage_report.csv")

    def metric(dataset, key):
        row = detail[(detail["dataset"] == dataset) & (detail["metric"] == key)]
        return int(row["value"].iloc[0]) if len(row) else "N/A"

    md = f"""# Data Quality / Cleaning Evidence
Regenerated by `scripts/generate_data_quality_evidence.md` from actual pipeline output CSVs
(`reports/data_quality_before.csv`, `reports/cleaning_report.csv`, `reports/cleaning_report_detail.csv`,
`reports/relationship_quality.csv`, `reports/join_coverage_report.csv`) — every number below is read
from a file the pipeline itself wrote, not hand-typed.

## 1. Cleaning summary (raw → cleaned)
{cleaning.to_markdown(index=False)}

## 2. Duplicates
| Dataset | Exact duplicate rows removed |
|---|---|
"""
    for _, row in cleaning.iterrows():
        md += f"| {row['dataset']} | {row['duplicates_removed']:,} |\n"

    md += f"""
## 3. Malformed IDs — normalized
- **transactions**: user_id/merchant_id/txn_id were already in a clean, single format in this file (verified, not assumed — see DATA_AUDIT.md §3.1).
- **kyc_records**: user_id had 6 distinct raw formats (USR12345, usr12345, USR-12345, USR 12345, USR_12345, bare 12345) — all normalized to `USR#####`.
- **merchants_master**: merchant_id had the same 6-format problem — normalized to `MCH####`.
- **chargebacks**: txn_id had 3 raw formats (TXN00012345, TXN12345, txn-00012345) — normalizing raised the match rate to fact_transactions from 89.4% to {coverage[coverage['relationship'].str.contains('chargebacks.txn_id')]['match_rate_pct'].iloc[0]}%.

## 4. Malformed currency/amount fields
- transactions.amount: {metric('transactions','amount_invalid_unparseable')} unparseable after cleaning (out of 20,000) — {metric('transactions','amount_negative_sign_flagged')} negative-sign values flagged (sign stripped, magnitude preserved, original preserved in `amount_raw`).
- kyc_records.monthly_income: {metric('kyc_records','income_disguised_null')} disguised-null values ("Not Available" etc.) correctly coerced to null, not 0.
- merchants_master.declared_avg_ticket_size: {metric('merchants_master','ticket_size_negative_flagged')} negative-sign values flagged.
- chargebacks.disputed_amount: {metric('chargebacks','disputed_amount_negative_flagged')} negative-sign values flagged.

## 5. Timestamp normalization
- transactions.timestamp: {metric('transactions','timestamp_epoch_converted')} raw Unix-epoch values detected and converted; {metric('transactions','timestamp_invalid_unparseable')} unparseable after cleaning.
- kyc_records.date_of_birth: epoch detection was extended to include **negative** epoch values (pre-1970 birth dates) after initial testing found 755 false "invalid" flags — see DATA_AUDIT.md changelog. After the fix: {metric('kyc_records','dob_invalid_unparseable')} genuinely unparseable.

## 6. Status / categorical normalization
- transactions.status: {metric('transactions','status_unrecognized_values')} unrecognized values after mapping 14 raw spellings to 4 controlled values.
- kyc_records.kyc_status: 16 raw spellings mapped to 4 controlled values.
- merchants_master.merchant_category: **82 raw labels → 12 canonical categories**, {metric('merchants_master','merchant_category_unmapped_values')} unmapped after the evidence-based remap (an earlier draft mapping, built without checking the full value_counts() output, left 3,731 values unmapped — caught in testing and rebuilt from the complete real value list).
- chargebacks.severity: {metric('chargebacks','severity_unrecognized_values')} unrecognized after collapsing 3 concurrent coding schemes (word/letter/P-code) into 4 controlled values (P-code mapping is a documented ASSUMPTION, not a data fact — see src/config.SEVERITY_MAP).
- chargebacks.reason_code: 34 raw labels → 6 canonical reasons.

## 7. Missing UTR / MCC
- UTR missing: {metric('transactions','utr_missing')} transactions ({metric('transactions','utr_missing')/20000*100:.1f}%) — never reconstructed.
- MCC missing: {metric('transactions','mcc_missing')} transactions ({metric('transactions','mcc_missing')/20000*100:.1f}%).

## 8. KYC / merchant identity-collision evidence
- {metric('kyc_records','user_id_identity_collision_rows'):,} of 36,122 cleaned KYC rows share a normalized user_id with at least one other row that has a DIFFERENT name/PAN.
- {metric('merchants_master','merchant_id_identity_collision_rows'):,} of 6,198 cleaned merchant rows share a normalized merchant_id with a different merchant_name.
- This is preserved as a flag column (`user_id_has_identity_collision`, `merchant_id_has_identity_collision`), not resolved by silent deduplication.

## 9. Relationship / join integrity
{relationship.to_markdown(index=False)}

## 10. Join coverage (propagated into every downstream analytics/dashboard output)
{coverage.to_markdown(index=False)}

## 11. Reproducibility evidence
This report and every number in it is regenerated by re-running, in order:
```
python scripts/run_pipeline.py                 # RAW -> cleaned Parquet + cleaning_report*.csv + data_quality_after.csv
python scripts/generate_analytics_reports.py    # -> join_coverage_report.csv + analytics_validation.md
python scripts/generate_data_quality_evidence.py  # -> this file
```
The full test suite (`pytest tests/`) re-validates every cleaning rule and several of the numbers above as regression guards (e.g. `test_kyc_identity_collision_flag_present`, `test_merchant_category_performance_no_categories_invented`, `test_relationship_match_rate_matches_audit_finding`).
"""
    (REPORTS_DIR / "DATA_QUALITY_EVIDENCE.md").write_text(md)
    print(f"Wrote {REPORTS_DIR / 'DATA_QUALITY_EVIDENCE.md'}")


if __name__ == "__main__":
    main()
