"""
Stage 10 — Graph-first AI Analyst: deterministic intent router.

Design (per the brief): a DETERMINISTIC analytics/query layer underneath
the natural-language interface. This router never executes arbitrary
code or SQL generated by an LLM - it matches the question against a
fixed set of supported intents (keyword/regex patterns), each of which
maps to one specific, already-tested Stage 5/6/7/8 function. If nothing
matches, the agent says so explicitly rather than guessing.

An optional LLM (Anthropic API) can be layered on top purely to improve
question PHRASING understanding (paraphrase -> intent) and to write the
final natural-language sentence - it never computes numbers itself. See
agent/llm_provider.py.
"""
import re
from dataclasses import dataclass


@dataclass
class Intent:
    name: str
    chart_type: str  # 'bar' | 'line' | 'table' | 'text' | 'network'
    description: str


# Ordered list: first matching pattern wins. Order matters (more specific first).
INTENT_PATTERNS: list[tuple[str, Intent]] = [
    (r"highest chargeback.to.transaction ratio|bonus question|chargeback ratio.*categor|categor.*chargeback ratio",
     Intent("bonus_chargeback_ratio_by_category", "bar", "Chargeback-to-transaction ratio by merchant category")),

    (r"riskiest merchant|high.?risk merchant|top risky merchant|merchant.*risk",
     Intent("riskiest_merchants", "bar", "Top merchants by explainable risk score")),

    (r"suspicious (transaction )?pattern|risky user|high.?risk user|suspicious user",
     Intent("suspicious_users", "table", "Users flagged by the explainable risk engine")),

    (r"largest chargeback categor|chargeback.*reason|reason.*chargeback|top.*dispute reason",
     Intent("chargeback_reasons", "bar", "Chargeback breakdown by reason code")),

    (r"suspicious network|network cluster|fraud ring|cluster|dense.*merchant|shared user",
     Intent("network_clusters", "network", "Dense merchant clusters / network structure")),

    (r"why is .* (considered )?high.?risk|why.*flagged|explain.*risk",
     Intent("explain_merchant_risk", "text", "Explanation of a specific merchant's risk score")),

    (r"transaction volume|volume by month|monthly trend|trend of transaction",
     Intent("transaction_volume_trend", "line", "Transaction volume/value trend over time")),

    (r"compare success(ful)? and fail|success.*failure|failed.*success",
     Intent("success_failure_comparison", "bar", "Successful vs failed transactions over time")),

    (r"average transaction value.*categor|categor.*average transaction",
     Intent("average_value_by_category", "bar", "Average transaction value across merchant categories")),

    (r"highest chargeback amount|merchant.*highest.*chargeback|which merchant.*chargeback",
     Intent("top_merchant_disputed_amount", "bar", "Merchant with the highest chargeback amount")),

    (r"most chargeback|highest.*chargeback.*user|which users.*chargeback",
     Intent("top_disputed_users", "bar", "Users with the highest number/amount of chargebacks")),

    (r"kpi|overview|summary|how (is|are) (we|things) doing|executive",
     Intent("kpi_overview", "text", "Executive KPI summary")),
]


def classify_question(question: str) -> Intent | None:
    """Returns the first matching Intent, or None if the question does
    not match any supported pattern (the agent must then say it cannot
    answer reliably, per the brief - never guess)."""
    q = question.strip().lower()
    for pattern, intent in INTENT_PATTERNS:
        if re.search(pattern, q):
            return intent
    return None


def extract_merchant_id(question: str) -> str | None:
    m = re.search(r"\bmch[\s\-_]?0*\d+\b", question, re.IGNORECASE)
    if not m:
        return None
    digits = re.sub(r"\D", "", m.group(0))
    return f"MCH{int(digits)}"
